# Generated by Django 5.2.5 on 2025-08-24 05:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2000)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('qualifications', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('employment_type', models.CharField(blank=True, max_length=50)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_content', models.TextField(blank=True)),
                ('scraping_method', models.CharField(default='beautifulsoup', max_length=50)),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('method_used', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('job_posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobassistant.jobposting')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('linkedin_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('professional_summary', models.TextField(blank=True)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level (0-2 years)'), ('mid', 'Mid Level (3-5 years)'), ('senior', 'Senior Level (6-10 years)'), ('lead', 'Lead/Principal (10+ years)'), ('executive', 'Executive/C-Level')], default='mid', max_length=20)),
                ('technical_skills', models.TextField(blank=True, help_text='Comma-separated list of technical skills')),
                ('soft_skills', models.TextField(blank=True, help_text='Comma-separated list of soft skills')),
                ('certifications', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('work_experience', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('parsed_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('cover_letter', 'Cover Letter'), ('resume', 'Tailored Resume')], max_length=20)),
                ('generation_method', models.CharField(choices=[('template', 'Template-based'), ('huggingface', 'Hugging Face Model'), ('ollama', 'Ollama Local Model'), ('openai', 'OpenAI GPT'), ('anthropic', 'Anthropic Claude')], max_length=20)),
                ('content', models.TextField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='generated/pdf/')),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='generated/docx/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('generation_time', models.FloatField(blank=True, null=True)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobassistant.jobposting')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobassistant.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
