# Generated by Django 5.2.5 on 2025-08-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobassistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='extraction_method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='site_domain',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
