# Generated by Django 5.2.5 on 2025-08-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobassistant', '0002_jobposting_extraction_method_jobposting_needs_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='application_instructions',
            field=models.TextField(blank=True),
        ),
    ]
