# Generated by Django 5.2.5 on 2025-08-24 09:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobassistant', '0004_alter_jobposting_application_instructions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressTask',
            fields=[
                ('task_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('job_scraping', 'Job Scraping'), ('resume_parsing', 'Resume Parsing'), ('document_generation', 'Document Generation'), ('other', 'Other')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='running', max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('stage', models.CharField(default='0/0', max_length=20)),
                ('status_message', models.CharField(default='Initializing...', max_length=500)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
