# Generated by Django 5.2.5 on 2025-08-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobassistant', '0005_progresstask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='availability',
            field=models.CharField(blank=True, choices=[('immediate', 'Immediate'), ('1_week', '1 Week'), ('2_weeks', '2 Weeks'), ('1_month', '1 Month'), ('negotiable', 'Negotiable')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city_region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='drivers_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='languages',
            field=models.TextField(blank=True, help_text='Languages and proficiency levels'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cv_photos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='professional_memberships',
            field=models.TextField(blank=True, help_text='JSON formatted memberships'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='projects',
            field=models.TextField(blank=True, help_text='JSON formatted project entries'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='references',
            field=models.TextField(blank=True, help_text='JSON formatted referee details'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='references_choice',
            field=models.CharField(choices=[('provided', 'References Provided'), ('on_request', 'Available on Request')], default='on_request', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visa_work_rights',
            field=models.CharField(blank=True, choices=[('nz_citizen', 'New Zealand Citizen'), ('au_citizen', 'Australian Citizen'), ('au_pr', 'Australian Permanent Resident'), ('nz_resident', 'New Zealand Resident'), ('open_work_visa', 'Open Work Visa'), ('employer_sponsored', 'Employer Sponsored Visa'), ('student_visa', 'Student Visa'), ('working_holiday', 'Working Holiday Visa'), ('other', 'Other (specify in notes)')], max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='volunteer_work',
            field=models.TextField(blank=True, help_text='JSON formatted volunteer work'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='achievements',
            field=models.TextField(blank=True, help_text='JSON formatted achievements'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='certifications',
            field=models.TextField(blank=True, help_text='JSON formatted certifications'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.TextField(blank=True, help_text='JSON formatted education entries'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='professional_summary',
            field=models.TextField(help_text='2-4 sentences highlighting your key strengths and career goals'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='soft_skills',
            field=models.TextField(blank=True, help_text='Soft skills separated by commas'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='technical_skills',
            field=models.TextField(blank=True, help_text='Technical skills separated by commas'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work_experience',
            field=models.TextField(blank=True, help_text='JSON formatted work experience entries'),
        ),
    ]
