# Generated by Django 5.2.5 on 2025-08-27 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobassistant', '0006_remove_userprofile_location_userprofile_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('date_received', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date_received', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('certification_number', models.CharField(blank=True, max_length=100)),
                ('verification_url', models.URLField(blank=True)),
                ('still_valid', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-issue_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_type', models.CharField(choices=[('high_school', 'High School Certificate'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate/PhD'), ('professional', 'Professional Qualification'), ('other', 'Other')], max_length=20)),
                ('field_of_study', models.CharField(max_length=200)),
                ('institution_name', models.CharField(max_length=200)),
                ('institution_location', models.CharField(max_length=200)),
                ('graduation_year', models.PositiveIntegerField()),
                ('gpa_grade', models.CharField(blank=True, max_length=20)),
                ('relevant_coursework', models.TextField(blank=True)),
                ('academic_achievements', models.TextField(blank=True)),
                ('thesis_project_title', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-graduation_year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('membership_type', models.CharField(choices=[('member', 'Member'), ('fellow', 'Fellow'), ('associate', 'Associate'), ('student', 'Student Member'), ('honorary', 'Honorary Member')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('personal', 'Personal'), ('professional', 'Professional'), ('academic', 'Academic'), ('open_source', 'Open Source'), ('freelance', 'Freelance')], max_length=20)),
                ('description', models.TextField()),
                ('role_responsibilities', models.TextField()),
                ('technologies_used', models.TextField(help_text='Comma-separated technologies')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('project_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('results_outcomes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('publication_name', models.CharField(max_length=200)),
                ('publication_date', models.DateField()),
                ('co_authors', models.CharField(blank=True, max_length=500)),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-publication_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('company_organization', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('relationship', models.CharField(choices=[('supervisor', 'Direct Supervisor'), ('manager', 'Manager'), ('colleague', 'Colleague'), ('client', 'Client'), ('mentor', 'Mentor'), ('professor', 'Professor/Teacher'), ('other', 'Other')], max_length=20)),
                ('relationship_description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('technical', 'Technical/Hard Skills'), ('software', 'Software Proficiency'), ('programming', 'Programming Languages'), ('soft', 'Soft Skills'), ('language', 'Language Skills'), ('industry', 'Industry-Specific Skills')], max_length=20)),
                ('proficiency_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert'), ('native', 'Native')], max_length=20)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('role_title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_active', models.BooleanField(default=False)),
                ('key_activities', models.TextField()),
                ('skills_gained', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('company_location', models.CharField(max_length=200)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('casual', 'Casual'), ('internship', 'Internship'), ('volunteer', 'Volunteer'), ('freelance', 'Freelance')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_working', models.BooleanField(default=False)),
                ('key_responsibilities', models.TextField()),
                ('key_achievements', models.TextField(blank=True)),
                ('skills_used', models.TextField(blank=True, help_text='Comma-separated skills')),
                ('reason_for_leaving', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.DeleteModel(
            name='AppSettings',
        ),
        migrations.RemoveField(
            model_name='scrapingsession',
            name='job_posting',
        ),
        migrations.AlterModelOptions(
            name='progresstask',
            options={},
        ),
        migrations.RenameField(
            model_name='progresstask',
            old_name='additional_data',
            new_name='result_data',
        ),
        migrations.RemoveField(
            model_name='progresstask',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='progresstask',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='progresstask',
            name='status_message',
        ),
        migrations.RemoveField(
            model_name='progresstask',
            name='task_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city_region',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='professional_memberships',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='references',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='references_choice',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='soft_skills',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='technical_skills',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='volunteer_work',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='progresstask',
            name='current_step',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_line_1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_line_2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='career_objectives',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='New Zealand', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('employed', 'Currently Employed'), ('unemployed', 'Currently Seeking'), ('student', 'Student'), ('freelancer', 'Freelancer/Consultant'), ('career_break', 'Career Break')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='landline_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_completion_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sections_completed',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state_region',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_industry',
            field=models.CharField(blank=True, choices=[('technology', 'Technology & IT'), ('finance', 'Finance & Banking'), ('healthcare', 'Healthcare & Medical'), ('education', 'Education & Training'), ('retail', 'Retail & Sales'), ('construction', 'Construction & Engineering'), ('hospitality', 'Hospitality & Tourism'), ('marketing', 'Marketing & Communications'), ('legal', 'Legal Services'), ('government', 'Government & Public Service'), ('manufacturing', 'Manufacturing'), ('consulting', 'Consulting'), ('non_profit', 'Non-Profit & NGO'), ('media', 'Media & Entertainment'), ('other', 'Other')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='value_proposition',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='willing_to_relocate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='progresstask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='progresstask',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='progresstask',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='progresstask',
            name='task_id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='availability',
            field=models.CharField(blank=True, choices=[('immediate', 'Immediate'), ('1_week', '1 Week'), ('2_weeks', '2 Weeks'), ('1_month', '1 Month'), ('negotiable', 'Negotiable')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='github_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='professional_summary',
            field=models.TextField(blank=True, default='', help_text='2-3 sentences highlighting your key strengths and career goals'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='visa_work_rights',
            field=models.CharField(blank=True, choices=[('nz_citizen', 'New Zealand Citizen'), ('au_citizen', 'Australian Citizen'), ('au_pr', 'Australian Permanent Resident'), ('nz_resident', 'New Zealand Resident'), ('open_work_visa', 'Open Work Visa'), ('employer_sponsored', 'Employer Sponsored Visa'), ('student_visa', 'Student Visa'), ('working_holiday', 'Working Holiday Visa'), ('other', 'Other (specify in notes)')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='award',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='jobassistant.userprofile'),
        ),
        migrations.AddField(
            model_name='certification',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='jobassistant.userprofile'),
        ),
        migrations.AddField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_entries', to='jobassistant.userprofile'),
        ),
        migrations.AddField(
            model_name='professionalmembership',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='jobassistant.userprofile'),
        ),
        migrations.AddField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='jobassistant.userprofile'),
        ),
        migrations.AddField(
            model_name='publication',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='jobassistant.userprofile'),
        ),
        migrations.AddField(
            model_name='reference',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='jobassistant.userprofile'),
        ),
        migrations.AddField(
            model_name='skill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='jobassistant.userprofile'),
        ),
        migrations.AddField(
            model_name='volunteerwork',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_work', to='jobassistant.userprofile'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='jobassistant.userprofile'),
        ),
        migrations.DeleteModel(
            name='GeneratedDocument',
        ),
        migrations.DeleteModel(
            name='ScrapingSession',
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('profile', 'name', 'category')},
        ),
    ]
