# Generated by Django 5.2.5 on 2025-08-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobassistant', '0007_professional_cv_rebuild_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
